### ISSUE TITLE
REPORTE ARCHITEC

### ISSUE THREAD

**Issue by KevCH24** [SistemasTecTlaxiaco/actividad-3-practica-architect-KevCH24#1]
[ACT 3 ARCHITEC.pdf](https://github.com/user-attachments/files/16841783/ACT.3.ARCHITEC.pdf)

**Comment by 22620229Angel** [comment]
20, El reporte esta bien elaborado :)

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
